name: Download CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install requirement
        run: |
          sudo apt update
          sudo apt install -y python3
          sudo apt install -y python3-pip
          sudo pip install -r requirements.txt
          mkdir download
      - name: start downloading the file
        run: |
          python3 __init__.py
          ls
          pwd
      - uses: actions/upload-artifact@master
        with:
          name: download
          path: download/
